# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dhivya Ravindran
title: Senior Data Scientist
email: dhivyaravindran@gmail.com
Phone: +1 (929) 404-6826

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: dhivyahandle
github_username:  maisonml
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dhivyar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Calendly scheduling page
  icon: fas fa-calendar
  url: https://calendly.com/dhivyaravindran
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/dhivya.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dhivya. Am a business-oriented Senior Data Scientist with ~7 years of full-time industry experience and 1+ years of pro bono experience in full stack Data Science, Machine Learning, Data Analytics and Software Engineering- starting with data collection from structured, semi-structured and un-structured data sources, to crunching data for insights, building Machine Learning models and algorithms, deploying the models/ algorithms into products and solutions, A/B testing, continuous monitoring and maintenance of the ML models and solutions.

  My specialties include: <mark>Product Data Science</mark>, <mark>e-Commerce</mark>, <mark>Retail</mark>, <mark>Fintech</mark>, <mark>Banking</mark> and <mark>Start-ups</mark>

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | # this will include new lines to allow paragraphs
          <mark>R</mark>, <mark>R Studio</mark>, <mark>R Markdown</mark>, <mark>R Shiny</mark>, <mark>Python</mark>, <mark>Pandas</mark>, <mark>Scikit- Learn</mark>, <mark>Jupyter Notebook</mark>,<mark>SQL</mark> (<mark>MySQL</mark>, <mark>Postgres</mark>), <mark>Git</mark>, <mark>GitHub</mark>, <mark>Version Control</mark>, <mark>ArcGIS</mark>, <mark>Tableau</mark>, <mark>Carto</mark>, <mark>ggplot2</mark>, <mark>dplyr</mark>, <mark>caret</mark>, <mark>reshape2</mark>, <mark>plyr</mark>, <mark>Amazon EC2</mark>, <mark>Redshift</mark>, <mark>AWS Lambda</mark>, <mark>Azure Machine Learning Studio</mark>, <mark>Azure Notebooks</mark>, Workspaces</mark>, <mark>Compute Instances</mark>, <mark>Azure Functions</mark>, <mark>Machine Learning</mark>- <mark>Linear/ Logistic Regression</mark>, <mark>Gradient Boosting Trees</mark>, <mark>Random Forests</mark>, <mark>Decision Trees</mark>, <mark>SVM</mark>, <mark>NLP</mark>, <mark>Recommendation Engines</mark>,

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IIM Calcutta (Top B- School in Asia)
        caption: 2012 - 2014
        sub_title: Executive Program in Global Business Management (EPGBM)
        quote: >
          Indian Institute of Management Calcutta (IIM Calcutta or IIM-C) is a public business school located in Joka, Kolkata, West Bengal, India. It was the first Indian Institute of Management to be established, and has been recognized as an Institute of National Importance by the government of India in 2017. 
        description: | # this will include new lines to allow paragraphs
          During my time at IIM Calcutta I secured "Excellent" grade in 8 out of 12 modules.

      - layout: left
        title: College of Engineering Guindy, Anna University (Asia's Oldest Technical Institution)
        caption: 2009 - 2011
        sub_title: MASTERS IN INDUSTRIAL ENGINEERING (M.E.)
        quote: >
          Indian Institute of Management Calcutta (IIM Calcutta or IIM-C) is a public business school located in Joka, Kolkata, West Bengal, India. It was the first Indian Institute of Management to be established, and has been recognized as an Institute of National Importance by the government of India in 2017. IIM Calcutta is one of only three triple accredited business schools in India, and the first to get the recognition. It is also the only business school in India which is a part of the CEMS Global Alliance in Management Education.
        description: | # this will include new lines to allow paragraphs
          CGPA: 8.91/ 10


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
